In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv(Path().resolve() / 'config' / '.env')

engine = create_engine(
    f"postgresql+psycopg2://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)
print("✅ Conectado!")

✅ Conectado!

In [2]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM weather_current ORDER BY collected_at DESC"))
    df = pd.DataFrame(result.fetchall(), columns=result.keys())

df

,id,city_name,country,latitude,longitude,temperature,feels_like,humidity,pressure,weather_main,weather_desc,wind_speed,sunrise,sunset,collected_at
0,2,Londrina,BR,-23.3103,-51.1628,27.81,28.59,54,1016,Clouds,nublado,2.57,2026-05-02 09:45:03+00:00,2026-05-02 20:58:04+00:00,2026-05-02 19:38:40.978582+00:00
1,1,São Paulo,BR,-23.5475,-46.6361,22.67,23.13,82,1019,Clear,céu limpo,5.14,2026-05-02 09:27:14+00:00,2026-05-02 20:39:40+00:00,2026-05-02 19:09:58.060874+00:00

In [5]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM weather_forecast ORDER BY collected_at DESC"))
    df = pd.DataFrame(result.fetchall(), columns=result.keys())

df

,id,city_name,country,latitude,longitude,forecast_time,temperature,feels_like,humidity,pressure,weather_main,weather_desc,wind_speed,pop,collected_at
0,1,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-02 21:00:00,28.80,33.02,74,1014,Clouds,nublado,1.12,0.00,2026-05-02 19:44:54.813607+00:00
1,2,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-03 00:00:00,27.92,30.77,72,1014,Clouds,nublado,0.69,0.00,2026-05-02 19:44:54.813607+00:00
2,3,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-03 03:00:00,28.25,31.16,70,1015,Clouds,nublado,0.95,0.00,2026-05-02 19:44:54.813607+00:00
3,4,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-03 06:00:00,26.80,28.90,75,1016,Clouds,nublado,2.28,0.00,2026-05-02 19:44:54.813607+00:00
4,5,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-03 09:00:00,26.78,29.34,81,1017,Rain,chuva leve,2.44,0.90,2026-05-02 19:44:54.813607+00:00
5,6,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-03 12:00:00,23.88,24.67,90,1020,Rain,chuva moderada,3.59,1.00,2026-05-02 19:44:54.813607+00:00
6,7,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-03 15:00:00,21.95,22.45,86,1020,Rain,chuva moderada,6.10,1.00,2026-05-02 19:44:54.813607+00:00
7,8,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-03 18:00:00,20.58,21.04,90,1020,Rain,chuva leve,4.02,1.00,2026-05-02 19:44:54.813607+00:00
8,9,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-03 21:00:00,21.01,21.33,83,1021,Rain,chuva leve,1.08,1.00,2026-05-02 19:44:54.813607+00:00
9,10,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-04 00:00:00,21.14,21.42,81,1022,Rain,chuva leve,1.57,1.00,2026-05-02 19:44:54.813607+00:00
10,11,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-04 03:00:00,21.03,21.28,80,1022,Rain,chuva leve,1.73,0.36,2026-05-02 19:44:54.813607+00:00
11,12,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-04 06:00:00,20.67,20.99,84,1020,Rain,chuva leve,2.11,0.20,2026-05-02 19:44:54.813607+00:00
12,13,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-04 09:00:00,20.06,20.42,88,1021,Rain,chuva leve,1.53,0.20,2026-05-02 19:44:54.813607+00:00
13,14,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-04 12:00:00,21.92,22.15,76,1022,Clouds,nublado,2.28,0.00,2026-05-02 19:44:54.813607+00:00
14,15,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-04 15:00:00,24.17,24.34,65,1021,Clouds,algumas nuvens,3.93,0.00,2026-05-02 19:44:54.813607+00:00
15,16,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-04 18:00:00,23.85,24.07,68,1019,Clouds,nuvens dispersas,4.71,0.00,2026-05-02 19:44:54.813607+00:00
16,17,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-04 21:00:00,22.96,23.14,70,1020,Clouds,nublado,4.14,0.00,2026-05-02 19:44:54.813607+00:00
17,18,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-05 00:00:00,21.49,21.65,75,1020,Clouds,nublado,3.05,0.00,2026-05-02 19:44:54.813607+00:00
18,19,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-05 03:00:00,20.84,21.02,78,1020,Clouds,nuvens dispersas,1.15,0.00,2026-05-02 19:44:54.813607+00:00
19,20,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-05 06:00:00,20.22,20.44,82,1019,Clouds,algumas nuvens,1.52,0.00,2026-05-02 19:44:54.813607+00:00
20,21,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-05 09:00:00,19.96,20.15,82,1019,Clear,céu limpo,1.96,0.00,2026-05-02 19:44:54.813607+00:00
21,22,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-05 12:00:00,23.54,23.73,68,1020,Clear,céu limpo,1.71,0.00,2026-05-02 19:44:54.813607+00:00
22,23,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-05 15:00:00,27.94,29.05,57,1019,Clear,céu limpo,0.86,0.00,2026-05-02 19:44:54.813607+00:00
23,24,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-05 18:00:00,27.49,28.91,62,1017,Clear,céu limpo,3.19,0.00,2026-05-02 19:44:54.813607+00:00
24,25,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-05 21:00:00,24.53,25.08,78,1018,Clear,céu limpo,2.20,0.00,2026-05-02 19:44:54.813607+00:00
25,26,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-06 00:00:00,24.06,24.61,80,1019,Clouds,nuvens dispersas,1.06,0.00,2026-05-02 19:44:54.813607+00:00
26,27,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-06 03:00:00,23.76,24.20,77,1019,Clouds,nublado,1.53,0.00,2026-05-02 19:44:54.813607+00:00
27,28,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-06 06:00:00,22.81,23.24,80,1018,Clouds,nublado,1.58,0.00,2026-05-02 19:44:54.813607+00:00
28,29,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-06 09:00:00,22.11,22.47,80,1018,Clear,céu limpo,1.83,0.00,2026-05-02 19:44:54.813607+00:00
29,30,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-06 12:00:00,25.38,25.72,67,1020,Clear,céu limpo,1.37,0.00,2026-05-02 19:44:54.813607+00:00
30,31,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-06 15:00:00,28.98,30.14,54,1018,Clear,céu limpo,1.23,0.00,2026-05-02 19:44:54.813607+00:00
31,32,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-06 18:00:00,28.31,29.68,58,1016,Clear,céu limpo,2.95,0.00,2026-05-02 19:44:54.813607+00:00
32,33,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-06 21:00:00,25.07,25.67,78,1016,Clouds,nuvens dispersas,1.87,0.00,2026-05-02 19:44:54.813607+00:00
33,34,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-07 00:00:00,24.48,25.10,81,1017,Rain,chuva leve,1.75,0.20,2026-05-02 19:44:54.813607+00:00
34,35,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-07 03:00:00,23.49,24.09,84,1017,Rain,chuva leve,1.43,0.52,2026-05-02 19:44:54.813607+00:00
35,36,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-07 06:00:00,22.53,23.08,86,1016,Clear,céu limpo,1.83,0.00,2026-05-02 19:44:54.813607+00:00
36,37,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-07 09:00:00,21.79,22.22,84,1016,Clear,céu limpo,2.29,0.00,2026-05-02 19:44:54.813607+00:00
37,38,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-07 12:00:00,25.00,25.41,71,1017,Clear,céu limpo,1.61,0.00,2026-05-02 19:44:54.813607+00:00
38,39,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-07 15:00:00,29.20,30.46,54,1015,Clear,céu limpo,1.34,0.00,2026-05-02 19:44:54.813607+00:00
39,40,Rio de Janeiro,BR,-22.9028,-43.2075,2026-05-07 18:00:00,28.95,30.37,56,1013,Clear,céu limpo,3.03,0.00,2026-05-02 19:44:54.813607+00:00