In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv(Path().resolve() / 'config' / '.env')

engine = create_engine(
    f"postgresql+psycopg2://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)
print("✅ Conectado!")

✅ Conectado!

In [2]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM weather_current ORDER BY collected_at DESC"))
    df = pd.DataFrame(result.fetchall(), columns=result.keys())

df

,id,city_name,country,latitude,longitude,temperature,feels_like,temp_min,temp_max,pressure,...,clouds,wind_speed,wind_deg,wind_gust,weather_main,weather_desc,sunrise,sunset,collected_at,inserted_at
0,3,Belo Horizonte,BR,-19.9208,-43.9378,27.89,27.78,27.46,28.44,1019,...,20,3.09,90,None,Clouds,algumas nuvens,2026-05-03 09:12:15+00:00,2026-05-03 20:32:53+00:00,2026-05-03 15:22:43.440135+00:00,2026-05-03 15:22:43.513427+00:00
1,2,Belo Horizonte,BR,-19.9208,-43.9378,27.89,27.78,27.46,28.44,1019,...,20,3.09,90,None,Clouds,algumas nuvens,2026-05-03 09:12:15+00:00,2026-05-03 20:32:53+00:00,2026-05-03 15:21:34.910110+00:00,2026-05-03 15:21:34.990100+00:00
2,1,Curitiba,BR,-25.5040,-49.2908,13.09,12.78,12.58,14.08,1024,...,100,5.14,70,None,Clouds,nublado,2026-05-03 09:40:56+00:00,2026-05-03 20:47:01+00:00,2026-05-03 15:21:14.166236+00:00,2026-05-03 15:21:14.321792+00:00

In [3]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM weather_forecast ORDER BY collected_at DESC"))
    df = pd.DataFrame(result.fetchall(), columns=result.keys())

df

,id,city_name,country,latitude,longitude,forecast_time,temperature,feels_like,temp_min,temp_max,...,wind_speed,wind_deg,wind_gust,weather_main,weather_desc,pop,rain_3h,visibility,collected_at,inserted_at
0,1,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-03 18:00:00,27.40,27.53,26.41,27.40,...,1.72,144,2.83,Clouds,nuvens dispersas,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
1,2,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-03 21:00:00,25.10,25.31,23.71,25.10,...,1.70,120,3.12,Rain,chuva leve,0.2,0.1,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
2,3,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-04 00:00:00,21.93,22.48,21.93,21.93,...,2.28,142,5.06,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
3,4,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-04 03:00:00,20.23,20.66,20.23,20.23,...,2.17,121,4.32,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
4,5,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-04 06:00:00,19.97,20.32,19.97,19.97,...,1.84,118,3.37,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
5,6,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-04 09:00:00,17.37,17.51,17.37,17.37,...,1.60,109,3.24,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
6,7,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-04 12:00:00,18.42,18.46,18.42,18.42,...,2.39,107,5.04,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
7,8,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-04 15:00:00,24.43,24.36,24.43,24.43,...,3.62,57,4.82,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
8,9,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-04 18:00:00,25.36,25.31,25.36,25.36,...,2.53,60,2.91,Clouds,nuvens dispersas,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
9,10,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-04 21:00:00,20.59,20.64,20.59,20.59,...,2.27,87,3.94,Clouds,nuvens dispersas,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
10,11,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-05 00:00:00,17.98,18.08,17.98,17.98,...,2.37,103,5.40,Clouds,nuvens dispersas,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
11,12,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-05 03:00:00,16.76,16.84,16.76,16.76,...,1.95,107,3.73,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
12,13,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-05 06:00:00,16.09,16.16,16.09,16.09,...,1.67,117,2.21,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
13,14,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-05 09:00:00,15.59,15.63,15.59,15.59,...,1.61,108,1.89,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
14,15,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-05 12:00:00,22.54,22.47,22.54,22.54,...,1.79,83,2.98,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
15,16,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-05 15:00:00,27.22,27.31,27.22,27.22,...,2.62,43,2.68,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
16,17,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-05 18:00:00,26.97,27.10,26.97,26.97,...,2.41,49,2.33,Clouds,algumas nuvens,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
17,18,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-05 21:00:00,21.82,21.83,21.82,21.82,...,1.43,88,2.33,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
18,19,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-06 00:00:00,18.83,18.99,18.83,18.83,...,1.90,107,3.50,Clouds,nuvens dispersas,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
19,20,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-06 03:00:00,17.80,17.96,17.80,17.80,...,1.60,118,1.80,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
20,21,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-06 06:00:00,16.99,17.12,16.99,16.99,...,1.58,119,1.60,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
21,22,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-06 09:00:00,16.26,16.32,16.26,16.26,...,1.50,125,1.40,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
22,23,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-06 12:00:00,23.12,23.11,23.12,23.12,...,1.81,80,3.53,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
23,24,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-06 15:00:00,27.49,27.24,27.49,27.49,...,3.31,56,4.07,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
24,25,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-06 18:00:00,27.45,27.21,27.45,27.45,...,3.70,52,3.86,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
25,26,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-06 21:00:00,21.40,21.21,21.40,21.40,...,2.23,77,5.58,Clouds,algumas nuvens,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
26,27,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-07 00:00:00,18.35,18.25,18.35,18.35,...,1.99,114,3.22,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
27,28,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-07 03:00:00,17.05,16.98,17.05,17.05,...,1.80,107,2.86,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
28,29,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-07 06:00:00,16.43,16.40,16.43,16.43,...,1.86,113,3.17,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
29,30,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-07 09:00:00,15.99,16.02,15.99,15.99,...,1.35,121,1.38,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
30,31,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-07 12:00:00,22.03,22.01,22.03,22.03,...,3.43,69,6.65,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
31,32,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-07 15:00:00,26.09,26.09,26.09,26.09,...,3.97,52,5.64,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
32,33,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-07 18:00:00,26.33,26.33,26.33,26.33,...,3.72,44,4.55,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
33,34,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-07 21:00:00,20.32,20.29,20.32,20.32,...,2.45,61,4.46,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
34,35,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-08 00:00:00,17.61,17.67,17.61,17.61,...,2.02,93,3.72,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
35,36,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-08 03:00:00,16.92,16.97,16.92,16.92,...,1.78,109,3.57,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
36,37,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-08 06:00:00,16.19,16.24,16.19,16.19,...,2.10,94,4.72,Clear,céu limpo,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
37,38,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-08 09:00:00,15.87,15.97,15.87,15.87,...,2.01,96,3.46,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
38,39,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-08 12:00:00,20.97,20.95,20.97,20.97,...,3.11,72,5.81,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00
39,40,Belo Horizonte,BR,-19.9208,-43.9378,2026-05-08 15:00:00,25.64,25.54,25.64,25.64,...,3.42,45,4.81,Clouds,nublado,0.0,NaN,10000,2026-05-03 15:22:44.043180+00:00,2026-05-03 15:22:44.113501+00:00

In [4]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM weather_pollution ORDER BY collected_at DESC"))
    df = pd.DataFrame(result.fetchall(), columns=result.keys())
# Convertendo para o time exato
df['collected_at'] = df['collected_at'].dt.tz_convert('America/Sao_Paulo')

df

,id,city_name,latitude,longitude,aqi,aqi_label,co,no,no2,o3,so2,pm2_5,pm10,nh3,collected_at,inserted_at
0,1,Belo Horizonte,-19.922732,-43.945095,2,Razoável,130.01,0.07,0.56,82.94,1.08,7.88,8.94,0.01,2026-05-03 12:22:44.878891-03:00,2026-05-03 15:22:44.986372+00:00